- nodes/node_duplicator.lua
- nodes/node_item_ejector.lua
After a failure to move the digtron with its metadata, some nodes were
broken. This worked around crashes that occurred if the inventory table
was missing.
> Create missing tables

- nodes/node_controllers.lua
Yes it works. It wouldn’t work with `local auto_cycle = function(pos)` form, however, due to different scoping rules.
> No need to make auto_cycle global

- util_execute_cycle.lua
This was probably forgotten in 5c0700456c09d2f5276572392d1c4e13b4b4d757
Fixes a crash encountered when damaging creatures while digging downward.
> Add missing items_dropped parameter 

- nodes/node_crate.lua
A missing return in on_dig callback for digtron:loaded_crate, makes crate corrupted if dug with certain tools, in particular technics drills.
> Avoid crate corruption when dug with special tools

- nodes/node_item_ejector.lua
Items can be duplicated by using multiple ejectors with one inventory.
One-liner fix, urgent I suppose.
> Update layout to prevent duplication during ejection

- nodes/node_crate.lua
This workaround forbids dropping the crates, so the servers should no
longer crash so often because of loaded digtron crates.
Known bugs: death can still cause dropped digtron crates, such as when the crates were moved into the crafting grid or when the player was run over by a train.
> Forbid dropping loaded digtron crates (see #44)

- util.lua
Changes `digtron.tap_batteries` function so that battery wear and charge is set directly to 0 instead of needlessly calculating it.
Fixes a crash that happens if a battery item doesn't define tool capabilities:
```
2020-03-07 13:44:30: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback node_on_receive_fields(): /data/world//worldmods/digtron/util.lua:272: attempt to index field 'fleshy' (a nil value)
2020-03-07 13:44:30: ERROR[Main]: stack traceback:
2020-03-07 13:44:30: ERROR[Main]: 	/data/world//worldmods/digtron/util.lua:272: in function 'tap_batteries'
2020-03-07 13:44:30: ERROR[Main]: 	/data/world//worldmods/digtron/util_execute_cycle.lua:376: in function 'f'
2020-03-07 13:44:30: ERROR[Main]: …
```
> Fix and simplify battery usage

- class_layout.lua
Metadata was previously lost according to my testing.
Now, the behaviour will be as specified in Minetest's lua_api.txt.
See https://github.com/minetest/minetest/blob/4b4513a67d9fc426d0f33798d0810a3a0594baaf/doc/lua_api.txt#L7315-L7316
> Change `after_dig_node()` callbacks to supply metadata as table.

- nodes/node_controllers.lua
Crashes otherwise on MT 5.3.0 if offset field is left empty.
Related: https://github.com/minetest/minetest/issues/10180
> auto_controller: Avoid nil error when digging slopes

- nodes/node_controllers.lua
- nodes/node_crate.lua
- nodes/node_diggers.lua
Eliminate warnings with use_texture_alpha in node definition in newer versions of minetest clients.
> Fix use_texture_alpha warnings.

- nodes/node_diggers.lua
`default:chest` is seen in underground dungeons. To keep them from interrupting the automation, this PR adds them to the list of nodes by putting all their contents into the inventory.
And yeah, I did a test too. Here is the footage:
https://github.com/minetest-mods/digtron/assets/55009343/5fe087da-8054-4711-8f81-7f5e84cf4f22
Wait... this may cause performance overhead even if there are no chests due to the additional `minetest.get_node(digpos)` call... IDK if this is a concern tho.
> Node diggers also eating dungeon chests

- nodes/node_builders.lua
This PR fixes the `use_texture_alpha` warning on the master builder, the only node involving textures with an alpha channel. As no transparency exists in used pixels, it is set to `"opaque"`.
No news is the good news. See, an ordinary master builder... except this time it is rendered with this PR.
> Fix use_texture_alpha warnings

- nodes/node_crate.lua
Preserves the crate name when unpacking and repacking a digtron. The name is only cleared if you break the empty crate.
> Preserve crate name when repacking digtron

- util_execute_cycle.lua
This PR tweaks the display of insufficient building materials. After this change, the text displayed will be changed from "Needed: mod:node" to "Needed: Node name (mod:node)".
> Display item description when missing item

- nodes/node_axle.lua
- nodes/node_controllers.lua
- util.lua
- util_execute_cycle.lua
This PR relaces deprecated calls. The following are fixed:
* Calls to `ObjectRef:moveto()` (Replaced by `ObjectRef:add_pos()` or `ObjectRef:move_to()` depending on engine version)
* Calls to `ObjectRef:setyaw()` (Replaced by `ObjectRef:set_yaw()`)
* Calling `MetaDataRef:set_string()` with `nil` as the second parameter (Replaced by `""`)
The following one is purposely not fixed:
https://github.com/minetest-mods/digtron/blob/64416fd07c16c7348e7f6481532f05e262644656/nodes/node_crate.lua#L296
> Fix deprecated function calls

- nodes/node_battery_holder.lua
This PR adds a check to the code of battery holders. Previously, if Technic is not installed, putting any item into the holder will crash the server. Now, they are rejected.
> Avoid crash if battery holder exists but technic not installed

- nodes/node_battery_holder.lua
This PR adds logging functions to the battery holders. This PR is ready for review.
> Log inventory actions on battery holders

- nodes/node_storage.lua
This PR redoes the list ring to allow moving fuel items in combined storage into the player's main storage by shift-clicking. Note that existing storages (both in-world and in-crate) are not updated.
> Allow moving fuel items in combined storage by shift-clicking

- util.lua
This PR fixes the owner moving twice when standing in front of their digtron. Previously, both `digtron.damage_creatures` and the main loop do this.
> Fix digtron owner moving twice when standing in front of their digtron

- nodes/node_battery_holder.lua
- nodes/node_builders.lua
- nodes/node_controllers.lua
- nodes/node_duplicator.lua
- nodes/node_storage.lua
- util.lua
This PR applies protections on inventory interactions of storage nodes.
> Apply area protections on storage nodes

- .luacheckrc
- class_layout.lua
- nodes/node_crate.lua
- nodes/node_duplicator.lua
- util.lua
This fixed errors caused by unknown nodes. core.registered_nodes[name] is nil in that case.
Fixes #112
@Pivert Please let me know whether this fixes your issue and whether there are any other errors that need fixing.
> Add unknown node definition fallback where needed
